#include    "resources/account/header.inc"
#include    "resources/account/function.inc"
#include    "resources/account/callback.inc"

#include    "resources/account/signature/header.inc"
#include    "resources/account/signature/function.inc"
#include    "resources/account/signature/callback.inc"

#include    "resources/account/admin/header.inc"
#include    "resources/account/admin/function.inc"
#include    "resources/account/admin/command.inc"
#include    "resources/account/admin/callback.inc"