#include    "resources/game/function.inc"

#include    "resources/game/tdm/header.inc"
#include    "resources/game/tdm/function.inc"
#include    "resources/game/tdm/callback.inc"

#include    "resources/game/dm/header.inc"
#include    "resources/game/dm/function.inc"
#include    "resources/game/dm/callback.inc"

#include    "resources/game/duel/header.inc"
#include    "resources/game/duel/function.inc"
#include    "resources/game/duel/callback.inc"

#include    "resources/game/copchase/header.inc"
#include    "resources/game/copchase/function.inc"
#include    "resources/game/copchase/callback.inc"

#include    "resources/game/freeroam/function.inc"
#include    "resources/game/freeroam/callback.inc"